-- schema.sql
-- ─────────────────────────────────────────────────────────────────────────────
-- PatchTicker — Database Schema
--
-- HOW TO APPLY
-- ─────────────
--   psql "$DATABASE_URL" -f schema.sql
--
-- This script is idempotent — safe to run multiple times.
-- All objects use CREATE IF NOT EXISTS / OR REPLACE.
--
-- SECURITY MODEL
-- ──────────────
--   1. TWO ROLES, LEAST PRIVILEGE
--      patchticker_owner  — owns all objects (run migrations, schema changes).
--                          Never used by the application. DBA access only.
--      patchticker_app    — application runtime role. Only the permissions the
--                          app actually needs. Revoked from everything else.
--
--   2. NO PUBLIC SCHEMA ACCESS
--      REVOKE CREATE ON SCHEMA public is applied to prevent the app role from
--      creating objects. Public access to pg_catalog is left at defaults.
--
--   3. ENCRYPTED PII COLUMNS
--      Sensitive user data (email, bug report text, user agents) is stored
--      encrypted using AES-256-GCM (encrypted by application layer, not pgcrypto).
--      Plaintext never touches the DB. Only the encryption key (DB_ENCRYPTION_KEY)
--      can recover the data.
--
--   4. HMAC LOOKUP COLUMNS
--      Because AES-GCM ciphertext is non-deterministic, equality lookups
--      (WHERE email = ?) use a separate HMAC-SHA256(email) column instead.
--      The HMAC uses the same DB_ENCRYPTION_KEY so it is useless without the key.
--
--   5. ROW-LEVEL SECURITY READY
--      RLS policies can be added per-table to enforce user-level isolation.
--      Structure is designed to support this (user_id foreign keys throughout).
--
--   6. NO PUBLIC PORT EXPOSURE
--      This schema assumes the DB is on a private network.
--      Port 5432 must not be open to the internet.
--      Access from the application server only via internal VPC / private network.
--      DBA access: SSH tunnel or bastion host only.
--
--      Platform-specific guidance:
--        Railway:     "Private Networking" is enabled by default. Use the
--                     private hostname (not the public TCP address) in DATABASE_URL.
--        Supabase:    Use the connection pooler (port 6543) via private network.
--                     Disable "Allow direct connections from internet" in dashboard.
--        Neon:        Use the pooled connection string. Private networking via
--                     IP allowlist or AWS PrivateLink.
--        AWS RDS:     Place in a private subnet. Use a security group that allows
--                     inbound 5432 only from the application server's security group.
--        Self-hosted: Bind pg_hba.conf to listen_addresses = 'localhost' or the
--                     private interface only. Never 0.0.0.0.
--
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Extensions ────────────────────────────────────────────────────────────────
-- uuid-ossp is not needed (UUIDs generated by the application layer).
-- pgcrypto is NOT used here — all encryption is done in the application layer
-- with Node.js crypto, so the encryption key never enters Postgres memory.

-- ── Roles ─────────────────────────────────────────────────────────────────────
-- These statements are idempotent — they do nothing if the roles already exist.

DO $$
BEGIN
  -- Owner role: runs migrations. Never used at application runtime.
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'patchticker_owner') THEN
    CREATE ROLE patchticker_owner NOLOGIN;
  END IF;

  -- App role: application runtime. Minimal permissions only.
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'patchticker_app') THEN
    -- NOINHERIT: role permissions are not inherited by child roles (defence-in-depth)
    -- NOCREATEDB, NOCREATEROLE: cannot create databases or roles
    -- NOSUPERUSER: never superuser
    CREATE ROLE patchticker_app
      NOLOGIN
      NOSUPERUSER
      NOCREATEDB
      NOCREATEROLE
      NOINHERIT;
  END IF;
END $$;

-- Remove default CREATE privilege on public schema from app role.
-- The app role must not be able to create objects.
REVOKE CREATE ON SCHEMA public FROM patchticker_app;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO patchticker_app;
GRANT USAGE ON SCHEMA public TO patchticker_owner;

-- ── Users table ───────────────────────────────────────────────────────────────
-- Stores registered accounts.
--
-- email_encrypted: AES-256-GCM ciphertext of the normalised email address.
--                  Format: hex(IV || auth_tag || ciphertext)
--                  Application decrypts on read. Never stored in plaintext.
--
-- email_hmac:      HMAC-SHA256(normalised_email, DB_ENCRYPTION_KEY) as hex.
--                  Used for WHERE email_hmac = $1 lookups.
--                  Deterministic — the same email always produces the same HMAC.
--                  UNIQUE constraint enforces one account per email.
--
-- password_hash:   argon2id hash string (e.g. $argon2id$v=19$m=65536,t=3,p=4$...).
--                  Already irreversible. Not encrypted (hashing is the right primitive).

CREATE TABLE IF NOT EXISTS users (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  email_encrypted  TEXT        NOT NULL,           -- AES-256-GCM ciphertext
  email_hmac       CHAR(64)    NOT NULL UNIQUE,     -- HMAC-SHA256 for lookup
  password_hash    TEXT        NOT NULL,            -- argon2id hash
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  users                  IS 'Registered user accounts. email is encrypted at rest.';
COMMENT ON COLUMN users.email_encrypted  IS 'AES-256-GCM ciphertext of email. Decrypt with DB_ENCRYPTION_KEY.';
COMMENT ON COLUMN users.email_hmac       IS 'HMAC-SHA256(email, DB_ENCRYPTION_KEY). Used for equality lookups. Never expose raw.';
COMMENT ON COLUMN users.password_hash    IS 'argon2id hash. Never decryptable. Re-hashed on login if parameters change.';

-- Index on email_hmac is implicit from the UNIQUE constraint.
-- Additional index on created_at for admin queries by registration date.
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (created_at DESC);

-- ── Refresh tokens table ──────────────────────────────────────────────────────
-- Server-side refresh token store. Replaces the in-memory Map in tokenService.js.
-- Raw tokens are never stored — only SHA-256 hashes.

CREATE TABLE IF NOT EXISTS refresh_tokens (
  token_hash       CHAR(64)    PRIMARY KEY,         -- SHA-256(raw_token) hex
  user_id          UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at       TIMESTAMPTZ NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  ip               TEXT,                            -- client IP at issuance
  user_agent       TEXT,                            -- UA at issuance (truncated to 200 chars)
  replaced         BOOLEAN     NOT NULL DEFAULT FALSE -- true = already rotated (replay detection)
);

COMMENT ON TABLE  refresh_tokens             IS 'Server-side refresh token store. Raw tokens never stored.';
COMMENT ON COLUMN refresh_tokens.token_hash  IS 'SHA-256 hex of the raw refresh token. One-way.';
COMMENT ON COLUMN refresh_tokens.replaced    IS 'If true, this token was already used. Presenting it again = replay attack.';

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id   ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);

-- ── Account lockout table ─────────────────────────────────────────────────────
-- Replaces the in-memory Map in lockoutService.js.
-- Keyed on email_hmac (same key as users table) so lockout records don't
-- expose emails even if this table is breached.

CREATE TABLE IF NOT EXISTS account_lockouts (
  email_hmac       CHAR(64)    PRIMARY KEY,         -- HMAC-SHA256(email) — same key as users
  attempts         SMALLINT    NOT NULL DEFAULT 0,
  first_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  locked_until     TIMESTAMPTZ                      -- NULL = not locked
);

COMMENT ON TABLE  account_lockouts            IS 'Login attempt tracking and lockout state. Email stored as HMAC.';
COMMENT ON COLUMN account_lockouts.email_hmac IS 'HMAC-SHA256(email, DB_ENCRYPTION_KEY). Matches users.email_hmac.';

CREATE INDEX IF NOT EXISTS idx_lockouts_locked_until ON account_lockouts (locked_until)
  WHERE locked_until IS NOT NULL;

-- ── Bug reports table ─────────────────────────────────────────────────────────
-- User-submitted bug reports. Free-text fields are encrypted at rest.

CREATE TABLE IF NOT EXISTS bug_reports (
  id                      BIGSERIAL   PRIMARY KEY,
  update_id               TEXT        NOT NULL,     -- validated enum from application
  severity                TEXT        NOT NULL,     -- 'low' | 'medium' | 'high' | 'critical'
  description_encrypted   TEXT        NOT NULL,     -- AES-256-GCM ciphertext of user description
  user_agent_encrypted    TEXT,                     -- AES-256-GCM ciphertext of UA string
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  bug_reports                        IS 'User-submitted bug reports. PII fields encrypted at rest.';
COMMENT ON COLUMN bug_reports.description_encrypted  IS 'AES-256-GCM ciphertext of description. Decrypt with DB_ENCRYPTION_KEY.';
COMMENT ON COLUMN bug_reports.user_agent_encrypted   IS 'AES-256-GCM ciphertext of User-Agent string.';

CREATE INDEX IF NOT EXISTS idx_bug_reports_update_id  ON bug_reports (update_id);
CREATE INDEX IF NOT EXISTS idx_bug_reports_created_at ON bug_reports (created_at DESC);

-- ── Grants — patchticker_app (runtime) ────────────────────────────────────────
-- Explicit allowlist: only what the application needs.
-- Nothing more is granted. Default is deny.

-- users: app can register users (INSERT), read for login (SELECT),
--        update for password re-hashing (UPDATE password_hash, updated_at).
--        No DELETE — account deletion requires a migration or owner action.
--        No SEQUENCE grant needed: id uses UUID DEFAULT gen_random_uuid(), not SERIAL.
GRANT SELECT, INSERT ON users TO patchticker_app;
GRANT UPDATE (password_hash, updated_at) ON users TO patchticker_app;

-- refresh_tokens: full lifecycle — create on login, read on verify,
--                 update replaced flag on rotation, delete on logout/expiry.
GRANT SELECT, INSERT, UPDATE, DELETE ON refresh_tokens TO patchticker_app;

-- account_lockouts: full lifecycle — read, create, update attempts/locked_until,
--                   and DELETE for clearAttempts() (on successful login) and
--                   forceUnlock() (admin unlock). Also called by cleanup_stale_lockouts().
GRANT SELECT, INSERT, UPDATE, DELETE ON account_lockouts TO patchticker_app;

-- bug_reports: submit new reports (INSERT), read for display (SELECT).
--              No UPDATE or DELETE.
GRANT SELECT, INSERT ON bug_reports TO patchticker_app;
GRANT USAGE ON SEQUENCE bug_reports_id_seq TO patchticker_app;

-- ── Grants — patchticker_owner (migrations) ───────────────────────────────────
GRANT ALL ON ALL TABLES IN SCHEMA public    TO patchticker_owner;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO patchticker_owner;
GRANT ALL ON SCHEMA public                  TO patchticker_owner;

-- ── Row-Level Security (structure ready, policies TBD) ───────────────────────
-- Uncomment and extend these when multi-tenant isolation is required.
-- ALTER TABLE users         ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE refresh_tokens ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE bug_reports   ENABLE ROW LEVEL SECURITY;
--
-- Example: users can only see their own refresh tokens:
-- CREATE POLICY refresh_tokens_own ON refresh_tokens
--   USING (user_id = current_setting('app.current_user_id')::UUID);

-- ── updated_at trigger ────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at ON users;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- ── Cleanup function (replaces in-memory setInterval) ────────────────────────
-- Call periodically from the application or a pg_cron job.

CREATE OR REPLACE FUNCTION cleanup_expired_tokens()
RETURNS INTEGER AS $$
DECLARE
  deleted INTEGER;
BEGIN
  DELETE FROM refresh_tokens WHERE expires_at < now();
  GET DIAGNOSTICS deleted = ROW_COUNT;
  RETURN deleted;
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION cleanup_expired_tokens() TO patchticker_app;

CREATE OR REPLACE FUNCTION cleanup_stale_lockouts(window_seconds INTEGER DEFAULT 1800)
RETURNS INTEGER AS $$
DECLARE
  deleted INTEGER;
BEGIN
  DELETE FROM account_lockouts
  WHERE
    (locked_until IS NULL AND first_attempt_at < now() - (window_seconds || ' seconds')::INTERVAL)
    OR (locked_until IS NOT NULL AND locked_until < now());
  GET DIAGNOSTICS deleted = ROW_COUNT;
  RETURN deleted;
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION cleanup_stale_lockouts(INTEGER) TO patchticker_app;
